/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#1a1919',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        'surface-bright': '#2c2c2c',
        'surface-variant': '#262626',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        'inverse-surface': '#fcf8f8',
        'inverse-on-surface': '#565554',
        'background': '#0e0e0e',
        'on-background': '#ffffff',
        'primary': '#f183ff',
        'primary-dim': '#eb65ff',
        'primary-fixed': '#ec6aff',
        'primary-fixed-dim': '#e64dff',
        'primary-container': '#ec6aff',
        'on-primary': '#540062',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#50005e',
        'on-primary-container': '#41004c',
        'inverse-primary': '#a300bc',
        'secondary': '#d97dff',
        'secondary-dim': '#d378f9',
        'secondary-fixed': '#f0c1ff',
        'secondary-fixed-dim': '#eaaeff',
        'secondary-container': '#721199',
        'on-secondary': '#41005b',
        'on-secondary-fixed': '#580079',
        'on-secondary-fixed-variant': '#7d21a4',
        'on-secondary-container': '#f0bfff',
        'tertiary': '#e1cfff',
        'tertiary-dim': '#c8b1f0',
        'tertiary-fixed': '#d6beff',
        'tertiary-fixed-dim': '#c8b1f0',
        'tertiary-container': '#d6beff',
        'on-tertiary': '#544178',
        'on-tertiary-fixed': '#362459',
        'on-tertiary-fixed-variant': '#544178',
        'on-tertiary-container': '#4b386e',
        'error': '#ff6e84',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
        'outline': '#777575',
        'outline-variant': '#494847',
        'surface-tint': '#f183ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        'headline': ['Epilogue', 'sans-serif'],
        'body': ['Be Vietnam Pro', 'sans-serif'],
        'label': ['Epilogue', 'sans-serif'],
      },
      boxShadow: {
        'glow': '0 0 32px rgba(84, 0, 98, 0.2)',
        'glow-fuchsia': '0 8px 32px rgba(241, 131, 255, 0.08)',
        'neon': '0 0 20px rgba(213, 0, 249, 0.15)',
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(213, 0, 249, 0.15)' },
          '50%': { boxShadow: '0 0 40px rgba(213, 0, 249, 0.3)' },
        },
      },
    },
  },
  plugins: [],
};