apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: valueskins-staging

resources:
  - ../../services/api-gateway/deployment.yml
  - ../../services/frontend/deployment.yml
  - ../../platform/redis/deployment.yml

patches:
  # Staging: fewer replicas, smaller resources
  - target:
      kind: Deployment
      name: api-gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: api-gateway
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 5
